services:
  - type: web
    name: auction-server
    runtime: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_BOT_URL
        fromService:
          type: web
          name: auction-bot
          property: host
      - key: MONGO_URI
        sync: false
    autoDeploy: false

  - type: web
    name: auction-bot
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r server/python_bot/requirements.txt
    startCommand: cd server/python_bot && gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: false
